### ISSUE TITLE
Is vpny_bybit compatible with vnpy 3.3.0?

### ISSUE THREAD

**Issue by cyberjunky** [vn-crypto/vnpy_bybit#8]
Hi, I'm just exploring vnpy and try to use this module to connect to Bybit.

If i import it like this in my run.py (on Ubuntu 22.04.1) 
```
from vnpy_bybiy import BybitGateway
```
I get the error
```
AtrributeError: BYBIT
```

Any idea what is wrong/or I do wrong?

**Comment by vn-crypto** [comment]
u need to use this extra patch module.
